version: "3"

services:
  app-test:
    restart: always
    build: .
    image: nahemah1022/sing-shpere:v1.0
    user: root
    environment:
      - GO_ENV=production
      - PORT=8000
      - TRANSCODE_INPUT_PATH=./s3
      - TRANSCODE_OUTPUT_PATH=./media
      - MQ_USER=singsphere
      - MQ_PASSWORD=singsphere123
    network_mode: "host"
    volumes:
      - go_mod:/go/pkg/mod
      - go_build:/root/.cache/go-build
      - /var/s3:/app/s3

volumes:
  go_mod:
  go_build:
