version: "3"

services:
  app:
    restart: always
    build: .
    image: nahemah1022/sing-shpere:v1.0
    environment:
      - GO_ENV=production
      - PORT=80
    network_mode: "host"
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: voice-server
    volumes:
      - go_mod:/go/pkg/mod
      - go_build:/root/.cache/go-build

volumes:
  go_mod:
  go_build:
